# Generated by Django 5.2.15 on 2026-07-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_object_id', models.PositiveBigIntegerField()),
                ('tran_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('validated', 'Validated'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('invalid', 'Invalid')], default='initiated', max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=120)),
                ('val_id', models.CharField(blank=True, max_length=120)),
                ('bank_tran_id', models.CharField(blank=True, max_length=120)),
                ('card_type', models.CharField(blank=True, max_length=120)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
